In [47]:
import pandas as pd

# Dictionary for DataFrame 1
student_data = {
    "Student_ID": [101, 102, 103],
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20]
}

# Dictionary for DataFrame 2
marks_data = {
    "Student_ID": [101, 102, 103],
    "Maths": [85, 90, 78],
    "Science": [88, 92, 81]
}

# Create DataFrames
df1 = pd.DataFrame(student_data)
df2 = pd.DataFrame(marks_data)

# Display DataFrames
print("DataFrame 1:")
print(df1)

print("\nDataFrame 2:")
print(df2)

DataFrame 1:
   Student_ID   Name  Age
0         101   Amit   21
1         102  Priya   22
2         103  Rahul   20

DataFrame 2:
   Student_ID  Maths  Science
0         101     85       88
1         102     90       92
2         103     78       81

In [48]:
merge_df = pd.merge(df1, df2, on="Student_ID")
print("\nMerged DataFrame:")
merge_df

Merged DataFrame:

   Student_ID   Name  Age  Maths  Science
0         101   Amit   21     85       88
1         102  Priya   22     90       92
2         103  Rahul   20     78       81

In [49]:
merge_df = pd.merge(df1, df2, on="Student_ID",how='inner')
print("\nMerged DataFrame:")
merge_df

Merged DataFrame:

   Student_ID   Name  Age  Maths  Science
0         101   Amit   21     85       88
1         102  Priya   22     90       92
2         103  Rahul   20     78       81

In [50]:
import pandas as pd

# Dictionary for DataFrame 1
student_data = {
    "Student_ID": [101, 102, 103],
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20]
}

# Dictionary for DataFrame 2
marks_data = {
    "Student_ID": [101, 102, 103],
    "Maths": [85, 90, 78],
    "Science": [88, 92, 81]
}

# Create DataFrames
df1 = pd.DataFrame(student_data)
df2 = pd.DataFrame(marks_data)

# Inner Join
result = pd.merge(df1, df2, on="Student_ID", how="inner")

print(result)

   Student_ID   Name  Age  Maths  Science
0         101   Amit   21     85       88
1         102  Priya   22     90       92
2         103  Rahul   20     78       81

In [51]:
merge_df = pd.merge(df1, df2, on="Student_ID",how='outer')
print("\nMerged DataFrame:")
merge_df

Merged DataFrame:

   Student_ID   Name  Age  Maths  Science
0         101   Amit   21     85       88
1         102  Priya   22     90       92
2         103  Rahul   20     78       81

In [52]:
df1 = pd.DataFrame({
    'User_ID':[101,102,103],
    'Name':['Alice','Bob','Charlie']
}, index=[11,22,33])
print(df1)

df2 = pd.DataFrame({
    'User_ID':[101,102,106],
    'City':['New York','London','Paris']
}, index=[100,200,300])
print(df2)

    User_ID     Name
11      101    Alice
22      102      Bob
33      103  Charlie
     User_ID      City
100      101  New York
200      102    London
300      106     Paris

In [53]:
index_access = pd.merge(df1,df2,left_index=True,right_index=True)
index_access

Empty DataFrame
Columns: [User_ID_x, Name, User_ID_y, City]
Index: []

In [54]:
df_21 = pd.DataFrame({
    'User_ID':[101,102,103],
    'Name':['Alice','Bob','Charlie']
}, index=[11,22,33])
print(df_21)

df_22 = pd.DataFrame({
    'User_ID':[101,102,106],
    'City':['New York','London','Paris']
}, index=[11,22,33])
print(df_22)

    User_ID     Name
11      101    Alice
22      102      Bob
33      103  Charlie
    User_ID      City
11      101  New York
22      102    London
33      106     Paris

In [55]:
index_access = pd.merge(df_21,df_22,left_index=True,right_index=True)
index_access

    User_ID_x     Name  User_ID_y      City
11        101    Alice        101  New York
22        102      Bob        102    London
33        103  Charlie        106     Paris

In [56]:
import numpy as np

In [57]:
data = {
    'Age':[25,np.nan,30,22,np.nan],
    'Score':[85,90,np.nan,75,80],
    'City':['New York','Paris','London',np.nan,'Paris']
}
dataf = pd.DataFrame(data)
print("Original DataFrame:")
print(dataf)

Original DataFrame:
    Age  Score      City
0  25.0   85.0  New York
1   NaN   90.0     Paris
2  30.0    NaN    London
3  22.0   75.0       NaN
4   NaN   80.0     Paris

### 1.Detect Missing Values

In [58]:
print(dataf.isnull())

     Age  Score   City
0  False  False  False
1   True  False  False
2  False   True  False
3  False  False   True
4   True  False  False

In [59]:
print(dataf.isnull().sum())

Age      2
Score    1
City     1
dtype: int64

# 2.Delete Missing values

In [60]:
df_clean_rows = dataf.dropna()
df_clean_rows

    Age  Score      City
0  25.0   85.0  New York

In [61]:
df_clean_cols = dataf.dropna(axis=1)
df_clean_cols

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [62]:
df_clean_subset = dataf.dropna(subset=['Age'])
df_clean_subset

    Age  Score      City
0  25.0   85.0  New York
2  30.0    NaN    London
3  22.0   75.0       NaN

# 3.Imput(fill) Missing Data

In [63]:
df_zero = dataf.fillna(0)

In [64]:
dataf['Age'] = dataf['Age'].fillna(df['Age'].mean())

In [65]:
dataf['City'] = dataf['City'].fillna(dataf['City'].mode()[0])

In [66]:
df_zero

    Age  Score      City
0  25.0   85.0  New York
1   0.0   90.0     Paris
2  30.0    0.0    London
3  22.0   75.0         0
4   0.0   80.0     Paris

In [67]:
dataf['Age']

0    25.000000
1    29.699118
2    30.000000
3    22.000000
4    29.699118
Name: Age, dtype: float64

In [68]:
dataf['City']

0    New York
1       Paris
2      London
3       Paris
4       Paris
Name: City, dtype: object