Pandas:-
1. what is pandas
2. Series = 1D,2D
3. Why Pandas
4. DataFrame
5. Reading Data
6. Exploring Data
7. Selection Data
8. Modifing Data
9. Sorting Data
10. Aggrigating Data
11. Handling Missing Value
12. Applying Function

# **1. Pandas**

In [ ]:
import pandas as pd
Var = [1,2,3,4]
pd.Series(Var)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
lab = ['y','a','s','h']
pd.Series(data=Var,index=lab)

y    1
a    2
s    3
h    4
dtype: int64

In [ ]:
list = [10,20,30,40]
pd.Series(list)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
D = pd.Series(list, index=lab)
print(D)

y    10
a    20
s    30
h    40
dtype: int64

In [ ]:
Data1 =[[10,20,30],[10,203,2]]
df_1 = pd.DataFrame(Data1)
print(type(df_1))
df_1

<class 'pandas.core.frame.DataFrame'>

    0    1   2
0  10   20  30
1  10  203   2

In [ ]:
df_2 = pd.DataFrame(Data1, columns = ['A','B','C'], index = ['a','b'])
df_2

    A    B   C
a  10   20  30
b  10  203   2

In [ ]:
Data =[('raj',89),('Tej',33),('alex',99)]
d = pd.DataFrame(Data, columns = ['Name','Marks'])
d

   Name  Marks
0   raj     89
1   Tej     33
2  alex     99

In [ ]:
dict = {
    'roll': [10,20,30,40,50],
    "name": ['radha','krisha','vishal','daksh','hardik']
}

In [ ]:
df = pd.DataFrame(dict)
df

   roll    name
0    10   radha
1    20  krisha
2    30  vishal
3    40   daksh
4    50  hardik

In [ ]:
nested_list =  [['yash',10],['daksh',33],['sef',33],['hardik',55]]
Data1 = pd.DataFrame(nested_list, columns = ['Name','age'])
Data1

     Name  age
0    yash   10
1   daksh   33
2     sef   33
3  hardik   55

In [ ]:
import numpy as np

d1 = np.array([1,2,3,4])
d2 = np.array([98,90,91,20])

Data_fr = {
    'df1':d1,
    'df2':d2
}

print(Data_fr)

{'df1': array([1, 2, 3, 4]), 'df2': array([98, 90, 91, 20])}

In [ ]:
import numpy as np

d1 = np.array([1,2,3,4])
d2 = np.array([98,90,91,20])

Data_fr = {
    'df1':d1,
    'df2':d2
}

print(Data_fr)

df_5 =pd.DataFrame(Data_fr)
print(df_5)

{'df1': array([1, 2, 3, 4]), 'df2': array([98, 90, 91, 20])}
   df1  df2
0    1   98
1    2   90
2    3   91
3    4   20

In [ ]:
# To upload files:
from google.colab import files
uploaded = files.upload()

Saving colors.csv to colors.csv

In [ ]:
pd.read_csv('colors.csv')

    1       Red,White,Green
0   2          White,Orange
1   3            White,Blue
2   4      Red,White,Orange
3   5              Red,Blue
4   6            White,Blue
5   7          White,Orange
6   8  Red,White,Blue,Green
7   9        Red,White,Blue
8  10                Yellow

In [ ]:
# To upload files:
from google.colab import files
uploaded = files.upload()

Saving continents.json to continents.json

In [ ]:
json_data = pd.read_json('continents.json')
# The actual list of continents is under the 'continents' key
df_continents = pd.DataFrame(json_data['continents'].tolist())
df_continents

,code,name,area_km2,population,countries,largest_country,highest_point
0,AF,Africa,30370000,1400000000,54,Algeria,Mount Kilimanjaro
1,AN,Antarctica,14000000,1000,0,None,Vinson Massif
2,AS,Asia,44579000,4700000000,49,Russia,Mount Everest
3,EU,Europe,10180000,750000000,44,Russia,Mount Elbrus
4,NA,North America,24709000,580000000,23,Canada,Denali
5,OC,Oceania,8525989,45000000,14,Australia,Puncak Jaya
6,SA,South America,17840000,430000000,12,Brazil,Aconcagua

In [ ]:
#Exploring Data

df = df_continents
df

,code,name,area_km2,population,countries,largest_country,highest_point
0,AF,Africa,30370000,1400000000,54,Algeria,Mount Kilimanjaro
1,AN,Antarctica,14000000,1000,0,None,Vinson Massif
2,AS,Asia,44579000,4700000000,49,Russia,Mount Everest
3,EU,Europe,10180000,750000000,44,Russia,Mount Elbrus
4,NA,North America,24709000,580000000,23,Canada,Denali
5,OC,Oceania,8525989,45000000,14,Australia,Puncak Jaya
6,SA,South America,17840000,430000000,12,Brazil,Aconcagua

In [ ]:
df.describe()

           area_km2    population  countries
count  7.000000e+00  7.000000e+00   7.000000
mean   2.145771e+07  1.129286e+09  28.000000
std    1.283040e+07  1.643615e+09  20.952327
min    8.525989e+06  1.000000e+03   0.000000
25%    1.209000e+07  2.375000e+08  13.000000
50%    1.784000e+07  5.800000e+08  23.000000
75%    2.753950e+07  1.075000e+09  46.500000
max    4.457900e+07  4.700000e+09  54.000000

In [ ]:
df.size

49

In [ ]:
df.isnull()

,code,name,area_km2,population,countries,largest_country,highest_point
0,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

code               0
name               0
area_km2           0
population         0
countries          0
largest_country    1
highest_point      0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(1)

In [ ]:
df.fillna(0)

,code,name,area_km2,population,countries,largest_country,highest_point
0,AF,Africa,30370000,1400000000,54,Algeria,Mount Kilimanjaro
1,AN,Antarctica,14000000,1000,0,0,Vinson Massif
2,AS,Asia,44579000,4700000000,49,Russia,Mount Everest
3,EU,Europe,10180000,750000000,44,Russia,Mount Elbrus
4,NA,North America,24709000,580000000,23,Canada,Denali
5,OC,Oceania,8525989,45000000,14,Australia,Puncak Jaya
6,SA,South America,17840000,430000000,12,Brazil,Aconcagua

In [ ]:
#Selecting Data:-
df.columns

Index(['code', 'name', 'area_km2', 'population', 'countries',
       'largest_country', 'highest_point'],
      dtype='object')

In [ ]:
df['name']

0           Africa
1       Antarctica
2             Asia
3           Europe
4    North America
5          Oceania
6    South America
Name: name, dtype: object

In [ ]:
df[['name','population']]

            name  population
0         Africa  1400000000
1     Antarctica        1000
2           Asia  4700000000
3         Europe   750000000
4  North America   580000000
5        Oceania    45000000
6  South America   430000000

In [ ]:
# Convert 'population' column to float type
df['population'] = df['population'].astype(float)

# Display the DataFrame info to verify the change
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   code             7 non-null      object
 1   name             7 non-null      object
 2   area_km2         7 non-null      int64
 3   population       7 non-null      float64
 4   countries        7 non-null      int64
 5   largest_country  6 non-null      object
 6   highest_point    7 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 524.0+ bytes

In [ ]:
df['full name'] = df['name'] + ' ' + df['population'].astype(str)
df['full name']

0          Africa 1400000000.0
1            Antarctica 1000.0
2            Asia 4700000000.0
3           Europe 750000000.0
4    North America 580000000.0
5           Oceania 45000000.0
6    South America 430000000.0
Name: full name, dtype: object

In [ ]:
type(df)

df.columns

Index(['code', 'name', 'area_km2', 'population', 'countries',
       'largest_country', 'highest_point', 'full name'],
      dtype='object')

In [ ]:
df.sort_values('area_km2',ascending=True).head(10)

,code,name,area_km2,population,countries,largest_country,highest_point,full name
5,OC,Oceania,8525989,4.500000e+07,14,Australia,Puncak Jaya,Oceania 45000000.0
3,EU,Europe,10180000,7.500000e+08,44,Russia,Mount Elbrus,Europe 750000000.0
1,AN,Antarctica,14000000,1.000000e+03,0,None,Vinson Massif,Antarctica 1000.0
6,SA,South America,17840000,4.300000e+08,12,Brazil,Aconcagua,South America 430000000.0
4,NA,North America,24709000,5.800000e+08,23,Canada,Denali,North America 580000000.0
0,AF,Africa,30370000,1.400000e+09,54,Algeria,Mount Kilimanjaro,Africa 1400000000.0
2,AS,Asia,44579000,4.700000e+09,49,Russia,Mount Everest,Asia 4700000000.0

In [ ]:
df = df.rename(columns={'area_km2': 'Area_square_km'})

In [ ]:
df.columns

Index(['code', 'name', 'Area_square_km', 'population', 'countries',
       'largest_country', 'highest_point', 'full name'],
      dtype='object')

In [ ]:
df.rename(columns = {'name':'Name','population':'Population'})

,code,Name,Area_square_km,Population,countries,largest_country,highest_point,full name
0,AF,Africa,30370000,1.400000e+09,54,Algeria,Mount Kilimanjaro,Africa 1400000000.0
1,AN,Antarctica,14000000,1.000000e+03,0,None,Vinson Massif,Antarctica 1000.0
2,AS,Asia,44579000,4.700000e+09,49,Russia,Mount Everest,Asia 4700000000.0
3,EU,Europe,10180000,7.500000e+08,44,Russia,Mount Elbrus,Europe 750000000.0
4,NA,North America,24709000,5.800000e+08,23,Canada,Denali,North America 580000000.0
5,OC,Oceania,8525989,4.500000e+07,14,Australia,Puncak Jaya,Oceania 45000000.0
6,SA,South America,17840000,4.300000e+08,12,Brazil,Aconcagua,South America 430000000.0